
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: appusers

test:
  <<: *default
  database: appusers_test

#
production:
  <<: *default
  database: appcredit_production
  username: appcredit
  password: <%= ENV['APPUSERS_PASSWORD'] %>